# azure-pipelines.yml
trigger:
  branches:
    include:
      - main   # Change if your default branch is different

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Reference secrets from Azure DevOps Library
  ADO_PAT: $(ADO_PAT)         # Your Azure DevOps PAT stored as secret
  GROQ_API_KEY: $(GROQ_API_KEY) # Your Groq API key stored as secret

steps:
# Step 1: Checkout code from GitHub
- checkout: self
  persistCredentials: true

# Step 2: Set up Python environment
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13'

# Step 3: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

# Step 4: Run Streamlit app
- script: |
    echo "Starting Streamlit Chatbot"
    export ADO_PAT=$(ADO_PAT)
    export GROQ_API_KEY=$(GROQ_API_KEY)
    streamlit run Chatbot-Test/streamlit_app.py --server.port 8501 --server.headless true
  displayName: 'Run Streamlit app'
